plugins {
    id 'java'
}

group 'ru.netology'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = 11
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testImplementation 'commons-dbutils:commons-dbutils:1.8.1'
    testImplementation 'com.mysql:mysql-connector-j:9.0.0'
}

test {
    useJUnitPlatform()
}